In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r"C:\Users\Decent\OneDrive\Documents\taimoor first important project for job.csv")

In [3]:
df. head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,8/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,8/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/6/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [4]:
df.shape

(9800, 18)

In [5]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales'],
      dtype='object')

In [6]:
df.describe

<bound method NDFrame.describe of       Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0          1  CA-2017-152156   8/11/2017  11/11/2017    Second Class
1          2  CA-2017-152156   8/11/2017  11/11/2017    Second Class
2          3  CA-2017-138688   12/6/2017  16/06/2017    Second Class
3          4  US-2016-108966  11/10/2016  18/10/2016  Standard Class
4          5  US-2016-108966  11/10/2016  18/10/2016  Standard Class
...      ...             ...         ...         ...             ...
9795    9796  CA-2017-125920  21/05/2017  28/05/2017  Standard Class
9796    9797  CA-2016-128608   12/1/2016  17/01/2016  Standard Class
9797    9798  CA-2016-128608   12/1/2016  17/01/2016  Standard Class
9798    9799  CA-2016-128608   12/1/2016  17/01/2016  Standard Class
9799    9800  CA-2016-128608   12/1/2016  17/01/2016  Standard Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer  United States        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9795    SH-19975     Sally Hughsby  Corporate  United States          Chicago
9796    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9797    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9798    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9799    CS-12490  Cindy Schnelling  Corporate  United States           Toledo

           State  Postal Code   Region       Product ID         Category  \
0       Kentucky      42420.0    South  FUR-BO-10001798        Furniture
1       Kentucky      42420.0    South  FUR-CH-10000454        Furniture
2     California      90036.0     West  OFF-LA-10000240  Office Supplies
3        Florida      33311.0    South  FUR-TA-10000577        Furniture
4        Florida      33311.0    South  OFF-ST-10000760  Office Supplies
...          ...          ...      ...              ...              ...
9795    Illinois      60610.0  Central  OFF-BI-10003429  Office Supplies
9796        Ohio      43615.0     East  OFF-AR-10001374  Office Supplies
9797        Ohio      43615.0     East  TEC-PH-10004977       Technology
9798        Ohio      43615.0     East  TEC-PH-10000912       Technology
9799        Ohio      43615.0     East  TEC-AC-10000487       Technology

     Sub-Category                                       Product Name     Sales
0       Bookcases                  Bush Somerset Collection Bookcase  261.9600
1          Chairs  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400
2          Labels  Self-Adhesive Address Labels for Typewriters b...   14.6200
3          Tables      Bretford CR4500 Series Slim Rectangular Table  957.5775
4         Storage                     Eldon Fold 'N Roll Cart System   22.3680
...           ...                                                ...       ...
9795      Binders  Cardinal HOLDit! Binder Insert Strips,Extra St...    3.7980
9796          Art           BIC Brite Liner Highlighters, Chisel Tip   10.3680
9797       Phones                                        GE 30524EE4  235.1880
9798       Phones           Anker 24W Portable Micro USB Car Charger   26.3760
9799  Accessories                SanDisk Cruzer 4 GB USB Flash Drive   10.3840

[9800 rows x 18 columns]>

In [8]:
df.isnull().sum

<bound method DataFrame.sum of       Row ID  Order ID  Order Date  Ship Date  Ship Mode  Customer ID  \
0      False     False       False      False      False        False
1      False     False       False      False      False        False
2      False     False       False      False      False        False
3      False     False       False      False      False        False
4      False     False       False      False      False        False
...      ...       ...         ...        ...        ...          ...
9795   False     False       False      False      False        False
9796   False     False       False      False      False        False
9797   False     False       False      False      False        False
9798   False     False       False      False      False        False
9799   False     False       False      False      False        False

      Customer Name  Segment  Country   City  State  Postal Code  Region  \
0             False    False    False  False  False        False   False
1             False    False    False  False  False        False   False
2             False    False    False  False  False        False   False
3             False    False    False  False  False        False   False
4             False    False    False  False  False        False   False
...             ...      ...      ...    ...    ...          ...     ...
9795          False    False    False  False  False        False   False
9796          False    False    False  False  False        False   False
9797          False    False    False  False  False        False   False
9798          False    False    False  False  False        False   False
9799          False    False    False  False  False        False   False

      Product ID  Category  Sub-Category  Product Name  Sales
0          False     False         False         False  False
1          False     False         False         False  False
2          False     False         False         False  False
3          False     False         False         False  False
4          False     False         False         False  False
...          ...       ...           ...           ...    ...
9795       False     False         False         False  False
9796       False     False         False         False  False
9797       False     False         False         False  False
9798       False     False         False         False  False
9799       False     False         False         False  False

[9800 rows x 18 columns]>

In [9]:
df.duplicated().sum

<bound method Series.sum of 0       False
1       False
2       False
3       False
4       False
        ...
9795    False
9796    False
9797    False
9798    False
9799    False
Length: 9800, dtype: bool>

In [10]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code      float64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
dtype: object

In [11]:
df.describe()

            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

In [12]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [17]:

df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)
df['Ship Date'] = pd.to_datetime(df['Ship Date'], dayfirst=True)

df.dtypes

Row ID                    int64
Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal Code             float64
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
dtype: object

In [18]:
df['Delivery Days'] = (df['Ship Date'] - df['Order Date']).dt.days


df['Delivery Days'].head(10)

0    3
1    3
2    4
3    7
4    7
5    5
6    5
7    5
8    5
9    5
Name: Delivery Days, dtype: int64

In [19]:
df['Order Year'] = df['Order Date'].dt.year
df['Order Month'] = df['Order Date'].dt.month


df[['Order Date', 'Order Year', 'Order Month']].head(10)

  Order Date  Order Year  Order Month
0 2017-11-08        2017           11
1 2017-11-08        2017           11
2 2017-06-12        2017            6
3 2016-10-11        2016           10
4 2016-10-11        2016           10
5 2015-06-09        2015            6
6 2015-06-09        2015            6
7 2015-06-09        2015            6
8 2015-06-09        2015            6
9 2015-06-09        2015            6

In [20]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Delivery Days,Order Year,Order Month
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,3,2017,11
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,2017,11
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,4,2017,6
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,7,2016,10
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,7,2016,10

In [21]:
print("Total Rows:", df.shape[0])
print("Total Columns:", df.shape[1])
print("Missing Values:", df.isnull().sum().sum())
print("Duplicate Rows:", df.duplicated().sum())

Total Rows: 9800
Total Columns: 21
Missing Values: 11
Duplicate Rows: 0

In [22]:

print(df.isnull().sum())


df['Postal Code'] = df['Postal Code'].fillna(0)


print("Missing Values After Fix:", df.isnull().sum().sum())

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Delivery Days     0
Order Year        0
Order Month       0
dtype: int64
Missing Values After Fix: 0

In [23]:
print("====== FINAL DATA CLEANING REPORT ======")
print("Total Rows:", df.shape[0])
print("Total Columns:", df.shape[1])
print("Missing Values:", df.isnull().sum().sum())
print("Duplicate Rows:", df.duplicated().sum())
print("Columns:", df.columns.tolist())
print("========================================")

====== FINAL DATA CLEANING REPORT ======
Total Rows: 9800
Total Columns: 21
Missing Values: 0
Duplicate Rows: 0
Columns: ['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Delivery Days', 'Order Year', 'Order Month']
========================================

In [24]:
df.dtypes

Row ID                    int64
Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal Code             float64
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
Delivery Days             int64
Order Year                int32
Order Month               int32
dtype: object

In [25]:
df.to_csv(r"C:\Users\Decent\OneDrive\Documents\superstore_cleaned.csv", index=False)

print("Clean file saved successfully!")
print("Total Rows:", df.shape[0])
print("Total Columns:", df.shape[1])
print("Missing Values:", df.isnull().sum().sum())

✅ Clean file saved successfully!
Total Rows: 9800
Total Columns: 21
Missing Values: 0

In [26]:

print("====== SUPERSTORE SALES ANALYSIS ======")
print()
print("1. Total Sales: $", round(df['Sales'].sum(), 2))
print()

# Sales by Region
print("2. Sales by Region:")
print(df.groupby('Region')['Sales'].sum().sort_values(ascending=False))
print()

# Sales by Category
print("3. Sales by Category:")
print(df.groupby('Category')['Sales'].sum().sort_values(ascending=False))
print()

# Sales by Segment
print("4. Sales by Segment:")
print(df.groupby('Segment')['Sales'].sum().sort_values(ascending=False))
print()

# Top 5 Products
print("5. Top 5 Products by Sales:")
print(df.groupby('Product Name')['Sales'].sum().sort_values(ascending=False).head())
print()

# Sales by Year
print("6. Sales by Year:")
print(df.groupby('Order Year')['Sales'].sum().sort_values(ascending=False))
print()

# Average Delivery Days
print("7. Average Delivery Days:", round(df['Delivery Days'].mean(), 1))
print()

# Average Delivery by Ship Mode
print("8. Average Delivery Days by Ship Mode:")
print(df.groupby('Ship Mode')['Delivery Days'].mean().sort_values())
print()

====== SUPERSTORE SALES ANALYSIS ======

1. Total Sales: $ 2261536.78

2. Sales by Region:
Region
West       710219.6845
East       669518.7260
Central    492646.9132
South      389151.4590
Name: Sales, dtype: float64

3. Sales by Category:
Category
Technology         827455.8730
Furniture          728658.5757
Office Supplies    705422.3340
Name: Sales, dtype: float64

4. Sales by Segment:
Segment
Consumer       1.148061e+06
Corporate      6.884941e+05
Home Office    4.249822e+05
Name: Sales, dtype: float64

5. Top 5 Products by Sales:
Product Name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
Name: Sales, dtype: float64

6. Sales by Year:
Order Year
2018    722052.0192
2017    600192.5500
2015    479856.2081
2016    459436.0054
Name: Sales, dtype: float64

7. Average Delivery Days: 4.0

8. Average Delivery Days by Ship Mode:
Ship Mode
Same Day          0.044610
First Class       2.179214
Second Class      3.249211
Standard Class    5.008363
Name: Delivery Days, dtype: float64

========================================

In [1]:
import pandas as pd
from sqlalchemy import create_engine

# 1. Load your cleaned CSV file from your specific file path
file_path = r"C:\Users\Decent\OneDrive\Documents\superstore_cleaned.csv"
df = pd.read_csv(file_path)

# 2. Define your exact SQL Database credentials
username = "root"
password = "Taimoor123$"
host = "localhost"
port = "3306"
database_name = "superstore_db"

# 3. Create the connection engine bridge
engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database_name}")

# 4. Export the data directly to MySQL
table_name = "cleaned_superstore_sales"
df.to_sql(name=table_name, con=engine, if_exists="replace", index=False)

print(f"🎉 Success! Your superstore data has been exported to MySQL table: '{table_name}'")

🎉 Success! Your superstore data has been exported to MySQL table: 'cleaned_superstore_sales'